plugins {
    id 'java'
    id 'application'
}

group = 'be.kdg.programming3'
version = '1.0.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

application {
    mainClass = 'be.kdg.programming3.onepiece.OnePieceApplication'
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}

tasks.named('run', JavaExec) {
    standardInput = System.in
}
