spring.application.name=OnePieceAppSpring
spring.profiles.active=memory
logging.level.be.kdg.programming3=DEBUG
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=none
